<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProfileLendersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('profile_lenders')->insert([
            'lender_id' => 1,
            'lender_profile_str' => 'BSN0001',
            'user_id' => 1,
            'lender_name' => 'Rajesh Kumar',
            'lender_mobile' => '9876543210',
            'lender_email' => 'admin@businessex.com',
            'lender_location' => '123 Business Park, Andheri East',
            'lender_city' => 'Mumbai',
            'lender_state' => 'Maharashtra',
            'lender_country' => 'India',
            'lender_adv_headline' => 'Getting Started with Business Growth',
            'lender_intro' => 'This is a sample description providing enough detail to be realistic for testing and development purposes.',
            'lender_type' => 1,
            'lender_occupation' => 'Featured',
            'lending_capacity' => 1000000.0000,
            'lending_interest_rate' => 12,
            'loan_offerings' => 'Term Loan',
            'prof_summary' => 'This is a sample description providing enough detail to be realistic for testing and development purposes.',
            'nbfc_contact_name' => 'Sample string data',
            'nbfc_contact_designation' => 'CEO',
            'nbfc_comp_name' => 'NBFC Finance Corp',
            'nbfc_type' => 1,
            'nbfc_branch' => 'Mumbai Main',
            'nbfc_country' => 'India',
            'nbfc_state' => 'Maharashtra',
            'nbfc_city' => 'Mumbai',
            'nbfc_pincode' => '400001',
            'nbfc_website' => 'https://example.com',
            'nbfc_about' => 'This is a sample description providing enough detail to be realistic for testing and development purposes.',
            'profile_pic_path' => 'uploads/images/sample1.jpg',
            'nbfc_corporate_profile_path' => 'uploads/images/sample1.jpg',
            'rbi_registered' => 0,
            'rbi_registered_no' => 'NBFC-12345',
            'lender_profile_status' => 0,
            'trackid' => 'TRK1000',
            'utm_source' => 'Featured',
            'utm_medium' => 'google',
            'utm_campaign' => 'google',
            'contact_response' => 5,
            'contact_status' => 0,
            'activated_by' => 1,
            'activated_at' => '2025-01-01 10:30:00',
            'last_login_at' => '2025-01-01 10:30:00'
        ]);

        DB::table('profile_lenders')->insert([
            'lender_id' => 2,
            'lender_profile_str' => 'INV0002',
            'user_id' => 2,
            'lender_name' => 'Priya Sharma',
            'lender_mobile' => '8765432109',
            'lender_email' => 'john.doe@example.com',
            'lender_location' => '456 Tech Hub, Whitefield',
            'lender_city' => 'Delhi',
            'lender_state' => 'Delhi',
            'lender_country' => 'United States',
            'lender_adv_headline' => 'Top Investment Strategies for 2025',
            'lender_intro' => 'A comprehensive overview of business strategies, growth opportunities, and market trends in the current landscape.',
            'lender_type' => 2,
            'lender_occupation' => 'Trending',
            'lending_capacity' => 1500000.0000,
            'lending_interest_rate' => 15,
            'loan_offerings' => 'Working Capital',
            'prof_summary' => 'A comprehensive overview of business strategies, growth opportunities, and market trends in the current landscape.',
            'nbfc_contact_name' => 'Another sample entry',
            'nbfc_contact_designation' => 'CTO',
            'nbfc_comp_name' => 'Capital Lending Ltd',
            'nbfc_type' => 2,
            'nbfc_branch' => 'Delhi Branch',
            'nbfc_country' => 'United States',
            'nbfc_state' => 'Delhi',
            'nbfc_city' => 'Delhi',
            'nbfc_pincode' => '110001',
            'nbfc_website' => 'https://linkedin.com/in/example',
            'nbfc_about' => 'A comprehensive overview of business strategies, growth opportunities, and market trends in the current landscape.',
            'profile_pic_path' => 'uploads/images/sample2.jpg',
            'nbfc_corporate_profile_path' => 'uploads/images/sample2.jpg',
            'rbi_registered' => 1,
            'rbi_registered_no' => 'NBFC-67890',
            'lender_profile_status' => 1,
            'trackid' => 'TRK1001',
            'utm_source' => 'Trending',
            'utm_medium' => 'facebook',
            'utm_campaign' => 'facebook',
            'contact_response' => 15,
            'contact_status' => 1,
            'activated_by' => 2,
            'activated_at' => '2025-02-02 10:30:00',
            'last_login_at' => '2025-02-02 10:30:00'
        ]);

        DB::table('profile_lenders')->insert([
            'lender_id' => 3,
            'lender_profile_str' => 'LEN0003',
            'user_id' => 3,
            'lender_name' => 'Amit Patel',
            'lender_mobile' => '7654321098',
            'lender_email' => 'priya.sharma@example.com',
            'lender_location' => '789 Corporate Tower, Connaught Place',
            'lender_city' => 'Bangalore',
            'lender_state' => 'Karnataka',
            'lender_country' => 'Singapore',
            'lender_adv_headline' => 'How to Scale Your Startup',
            'lender_intro' => 'Detailed analysis covering key aspects of business operations, market competition, and potential areas for expansion.',
            'lender_type' => 3,
            'lender_occupation' => 'Latest',
            'lending_capacity' => 2000000.0000,
            'lending_interest_rate' => 18,
            'loan_offerings' => 'Equipment Finance',
            'prof_summary' => 'Detailed analysis covering key aspects of business operations, market competition, and potential areas for expansion.',
            'nbfc_contact_name' => 'Third sample value',
            'nbfc_contact_designation' => 'Managing Director',
            'nbfc_comp_name' => 'QuickLoan Finance',
            'nbfc_type' => 3,
            'nbfc_branch' => 'Bangalore Office',
            'nbfc_country' => 'Singapore',
            'nbfc_state' => 'Karnataka',
            'nbfc_city' => 'Bangalore',
            'nbfc_pincode' => '560001',
            'nbfc_website' => 'https://company.com',
            'nbfc_about' => 'Detailed analysis covering key aspects of business operations, market competition, and potential areas for expansion.',
            'profile_pic_path' => 'uploads/images/sample3.jpg',
            'nbfc_corporate_profile_path' => 'uploads/images/sample3.jpg',
            'rbi_registered' => 0,
            'rbi_registered_no' => 'NBFC-11223',
            'lender_profile_status' => 0,
            'trackid' => 'TRK1002',
            'utm_source' => 'Latest',
            'utm_medium' => 'linkedin',
            'utm_campaign' => 'linkedin',
            'contact_response' => 25,
            'contact_status' => 0,
            'activated_by' => 3,
            'activated_at' => '2025-03-03 10:30:00',
            'last_login_at' => '2025-03-03 10:30:00'
        ]);

    }
}