<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProfileBusinessTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('profile_business')->insert([
            'business_id' => 1,
            'business_profile_str' => 'BSN0001',
            'user_id' => 1,
            'seller_name' => 'Rajesh Kumar',
            'seller_designation' => 'CEO',
            'seller_mobile' => '9876543210',
            'seller_email' => 'admin@businessex.com',
            'advmt_headline' => 'Getting Started with Business Growth',
            'seller_intro' => 'Sample description text.',
            'seller_company' => 'Sample string data',
            'estb_year' => 2010,
            'emp_count' => 2,
            'entity_type' => 1,
            'business_type' => 1,
            'industry_sector' => 'Featured',
            'business_website' => 'https://example.com',
            'facilities_desc' => 'This is a sample description providing enough detail to be realistic for testing and development purposes.',
            'annual_sales' => 1000000.0000,
            'ebitda' => 15.0000,
            'gross_profit' => '5000000',
            'inventory_value' => '5000000',
            'ebitda_margin' => 15.0000,
            'rentals' => '5000000',
            'company_summary' => 'This is a sample description providing enough detail to be realistic for testing and development purposes.',
            'director_name' => 'Rajesh Kumar',
            'director_email' => 'admin@businessex.com',
            'director_designation' => 'CEO',
            'ofc_address' => '123 Business Park, Andheri East',
            'ofc_city' => 'Mumbai',
            'ofc_state' => 'Maharashtra',
            'ofc_country' => 'India',
            'ofc_pincode' => '400001',
            'business_pitch' => 'Sample description text.',
            'seeking_investors' => 0,
            'seeking_buyers' => 0,
            'seeking_loan' => 0,
            'seeking_mentors' => 0,
            'seeking_accelerators' => 0,
            'buyer_sell_price' => 1000000.0000,
            'buyer_sell_reason' => 'Sample description text.',
            'inv_for' => 1,
            'inv_asking_price' => 1000000.0000,
            'inv_stake' => '20%',
            'inv_reason' => 'Sample description text.',
            'loan_collateral_details' => 'Sample description text.',
            'loan_amount' => 1000000.0000,
            'loan_repayment_period' => '12 months',
            'loan_interest_rate' => 12,
            'loan_reason' => 'Sample description text.',
            'loan_existing' => 'Existing home loan of 20L',
            'mentor_req_details' => 'Sample description text.',
            'accel_req_details' => 'Sample description text.',
            'accel_inv_req' => '1000000',
            'accel_time_period' => '6 months',
            'seller_prof_pic' => 'uploads/images/sample1.jpg',
            'seller_prof_thumb_pic' => 'uploads/images/sample1.jpg',
            'seller_prof_thumb_pic1' => 'uploads/images/sample1.jpg',
            'seller_prof_pic1' => 'uploads/images/sample1.jpg',
            'seller_doc_path' => 'uploads/docs/doc1.pdf',
            'seller_doc_path1' => 'uploads/docs/doc1.pdf',
            'seller_doc_path2' => 'uploads/docs/doc1.pdf',
            'seller_doc_path3' => 'uploads/docs/doc1.pdf',
            'seller_doc_path4' => 'uploads/docs/doc1.pdf',
            'business_profile_status' => 0,
            'membership_paid' => 1,
            'membership_plan' => 1,
            'seller_prof_thumb_pic_name' => 'uploads/images/sample1.jpg',
            'trackid' => 'TRK1000',
            'utm_source' => 'Featured',
            'utm_medium' => 'google',
            'utm_campaign' => 'google',
            'mailer_campaign' => 0,
            'contact_response' => 5,
            'contact_status' => 0,
            'activated_by' => 1,
            'activated_at' => '2025-01-01 10:30:00',
            'last_login_at' => '2025-01-01 10:30:00'
        ]);

        DB::table('profile_business')->insert([
            'business_id' => 2,
            'business_profile_str' => 'INV0002',
            'user_id' => 2,
            'seller_name' => 'Priya Sharma',
            'seller_designation' => 'CTO',
            'seller_mobile' => '8765432109',
            'seller_email' => 'john.doe@example.com',
            'advmt_headline' => 'Top Investment Strategies for 2025',
            'seller_intro' => 'Another sample description.',
            'seller_company' => 'Another sample entry',
            'estb_year' => 2013,
            'emp_count' => 3,
            'entity_type' => 2,
            'business_type' => 2,
            'industry_sector' => 'Trending',
            'business_website' => 'https://linkedin.com/in/example',
            'facilities_desc' => 'A comprehensive overview of business strategies, growth opportunities, and market trends in the current landscape.',
            'annual_sales' => 1500000.0000,
            'ebitda' => 20.0000,
            'gross_profit' => '10000000',
            'inventory_value' => '10000000',
            'ebitda_margin' => 20.0000,
            'rentals' => '10000000',
            'company_summary' => 'A comprehensive overview of business strategies, growth opportunities, and market trends in the current landscape.',
            'director_name' => 'Priya Sharma',
            'director_email' => 'john.doe@example.com',
            'director_designation' => 'CTO',
            'ofc_address' => '456 Tech Hub, Whitefield',
            'ofc_city' => 'Delhi',
            'ofc_state' => 'Delhi',
            'ofc_country' => 'United States',
            'ofc_pincode' => '110001',
            'business_pitch' => 'Another sample description.',
            'seeking_investors' => 1,
            'seeking_buyers' => 1,
            'seeking_loan' => 1,
            'seeking_mentors' => 1,
            'seeking_accelerators' => 1,
            'buyer_sell_price' => 1500000.0000,
            'buyer_sell_reason' => 'Another sample description.',
            'inv_for' => 2,
            'inv_asking_price' => 1500000.0000,
            'inv_stake' => '35%',
            'inv_reason' => 'Another sample description.',
            'loan_collateral_details' => 'Another sample description.',
            'loan_amount' => 1500000.0000,
            'loan_repayment_period' => '24 months',
            'loan_interest_rate' => 15,
            'loan_reason' => 'Another sample description.',
            'loan_existing' => 'No existing loans',
            'mentor_req_details' => 'Another sample description.',
            'accel_req_details' => 'Another sample description.',
            'accel_inv_req' => '5000000',
            'accel_time_period' => '12 months',
            'seller_prof_pic' => 'uploads/images/sample2.jpg',
            'seller_prof_thumb_pic' => 'uploads/images/sample2.jpg',
            'seller_prof_thumb_pic1' => 'uploads/images/sample2.jpg',
            'seller_prof_pic1' => 'uploads/images/sample2.jpg',
            'seller_doc_path' => 'uploads/docs/doc2.pdf',
            'seller_doc_path1' => 'uploads/docs/doc2.pdf',
            'seller_doc_path2' => 'uploads/docs/doc2.pdf',
            'seller_doc_path3' => 'uploads/docs/doc2.pdf',
            'seller_doc_path4' => 'uploads/docs/doc2.pdf',
            'business_profile_status' => 1,
            'membership_paid' => 2,
            'membership_plan' => 2,
            'seller_prof_thumb_pic_name' => 'uploads/images/sample2.jpg',
            'trackid' => 'TRK1001',
            'utm_source' => 'Trending',
            'utm_medium' => 'facebook',
            'utm_campaign' => 'facebook',
            'mailer_campaign' => 1,
            'contact_response' => 15,
            'contact_status' => 1,
            'activated_by' => 2,
            'activated_at' => '2025-02-02 10:30:00',
            'last_login_at' => '2025-02-02 10:30:00'
        ]);

        DB::table('profile_business')->insert([
            'business_id' => 3,
            'business_profile_str' => 'LEN0003',
            'user_id' => 3,
            'seller_name' => 'Amit Patel',
            'seller_designation' => 'Managing Director',
            'seller_mobile' => '7654321098',
            'seller_email' => 'priya.sharma@example.com',
            'advmt_headline' => 'How to Scale Your Startup',
            'seller_intro' => 'Third sample description.',
            'seller_company' => 'Third sample value',
            'estb_year' => 2016,
            'emp_count' => 4,
            'entity_type' => 3,
            'business_type' => 3,
            'industry_sector' => 'Latest',
            'business_website' => 'https://company.com',
            'facilities_desc' => 'Detailed analysis covering key aspects of business operations, market competition, and potential areas for expansion.',
            'annual_sales' => 2000000.0000,
            'ebitda' => 25.0000,
            'gross_profit' => '25000000',
            'inventory_value' => '25000000',
            'ebitda_margin' => 25.0000,
            'rentals' => '25000000',
            'company_summary' => 'Detailed analysis covering key aspects of business operations, market competition, and potential areas for expansion.',
            'director_name' => 'Amit Patel',
            'director_email' => 'priya.sharma@example.com',
            'director_designation' => 'Managing Director',
            'ofc_address' => '789 Corporate Tower, Connaught Place',
            'ofc_city' => 'Bangalore',
            'ofc_state' => 'Karnataka',
            'ofc_country' => 'Singapore',
            'ofc_pincode' => '560001',
            'business_pitch' => 'Third sample description.',
            'seeking_investors' => 0,
            'seeking_buyers' => 0,
            'seeking_loan' => 0,
            'seeking_mentors' => 0,
            'seeking_accelerators' => 0,
            'buyer_sell_price' => 2000000.0000,
            'buyer_sell_reason' => 'Third sample description.',
            'inv_for' => 3,
            'inv_asking_price' => 2000000.0000,
            'inv_stake' => '50%',
            'inv_reason' => 'Third sample description.',
            'loan_collateral_details' => 'Third sample description.',
            'loan_amount' => 2000000.0000,
            'loan_repayment_period' => '36 months',
            'loan_interest_rate' => 18,
            'loan_reason' => 'Third sample description.',
            'loan_existing' => 'Business loan of 50L',
            'mentor_req_details' => 'Third sample description.',
            'accel_req_details' => 'Third sample description.',
            'accel_inv_req' => '10000000',
            'accel_time_period' => '18 months',
            'seller_prof_pic' => 'uploads/images/sample3.jpg',
            'seller_prof_thumb_pic' => 'uploads/images/sample3.jpg',
            'seller_prof_thumb_pic1' => 'uploads/images/sample3.jpg',
            'seller_prof_pic1' => 'uploads/images/sample3.jpg',
            'seller_doc_path' => 'uploads/docs/doc3.pdf',
            'seller_doc_path1' => 'uploads/docs/doc3.pdf',
            'seller_doc_path2' => 'uploads/docs/doc3.pdf',
            'seller_doc_path3' => 'uploads/docs/doc3.pdf',
            'seller_doc_path4' => 'uploads/docs/doc3.pdf',
            'business_profile_status' => 0,
            'membership_paid' => 3,
            'membership_plan' => 3,
            'seller_prof_thumb_pic_name' => 'uploads/images/sample3.jpg',
            'trackid' => 'TRK1002',
            'utm_source' => 'Latest',
            'utm_medium' => 'linkedin',
            'utm_campaign' => 'linkedin',
            'mailer_campaign' => 2,
            'contact_response' => 25,
            'contact_status' => 0,
            'activated_by' => 3,
            'activated_at' => '2025-03-03 10:30:00',
            'last_login_at' => '2025-03-03 10:30:00'
        ]);

    }
}