<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProfileInvestorTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('profile_investor')->insert([
            'investor_id' => 1,
            'inv_profile_str' => 'BSN0001',
            'user_id' => 1,
            'inv_name' => 'Rajesh Kumar',
            'inv_email' => 'admin@businessex.com',
            'inv_mobile' => '9876543210',
            'inv_placeid' => 'Sample string data',
            'inv_city' => 'Mumbai',
            'inv_state' => 'Maharashtra',
            'inv_country' => 'India',
            'inv_headline' => 'Getting Started with Business Growth',
            'inv_intro' => 'This is a sample description providing enough detail to be realistic for testing and development purposes.',
            'inv_type' => 1,
            'firm_type' => 1,
            'invest_size_min' => 1000.0000,
            'invest_size_max' => 1000.0000,
            'invest_pref' => 1,
            'invest_stake' => 20,
            'full_acquisition' => 0,
            'purchase_capacity_min' => 50000000.0000,
            'purchase_capacity_max' => 50000000.0000,
            'inv_abt_urself' => 'Experienced angel investor with 10+ years.',
            'linkedin_profile' => 'https://example.com',
            'company_name' => 'TechVista Solutions Pvt Ltd',
            'company_designation' => 'CEO',
            'company_placeid' => 'Sample string data',
            'company_city' => 'Mumbai',
            'company_state' => 'Maharashtra',
            'company_country' => 'India',
            'company_pincode' => '400001',
            'company_website' => 'https://example.com',
            'company_logo_path' => 'uploads/images/sample1.jpg',
            'company_summary' => 'This is a sample description providing enough detail to be realistic for testing and development purposes.',
            'inv_profile_pic_path' => 'uploads/images/sample1.jpg',
            'inv_profile_status' => 0,
            'membership_paid' => 1,
            'membership_plan' => 1,
            'inv_profile_pic_name' => 'uploads/images/sample1.jpg',
            'trackid' => 'TRK1000',
            'utm_source' => 'Featured',
            'utm_medium' => 'google',
            'utm_campaign' => 'google',
            'contact_response' => 5,
            'contact_status' => 0,
            'activated_by' => 1,
            'activated_at' => '2025-01-01 10:30:00',
            'last_login_at' => '2025-01-01 10:30:00',
            'reg_source' => 1
        ]);

        DB::table('profile_investor')->insert([
            'investor_id' => 2,
            'inv_profile_str' => 'INV0002',
            'user_id' => 2,
            'inv_name' => 'Priya Sharma',
            'inv_email' => 'john.doe@example.com',
            'inv_mobile' => '8765432109',
            'inv_placeid' => 'Another sample entry',
            'inv_city' => 'Delhi',
            'inv_state' => 'Delhi',
            'inv_country' => 'United States',
            'inv_headline' => 'Top Investment Strategies for 2025',
            'inv_intro' => 'A comprehensive overview of business strategies, growth opportunities, and market trends in the current landscape.',
            'inv_type' => 2,
            'firm_type' => 2,
            'invest_size_min' => 1250.0000,
            'invest_size_max' => 1250.0000,
            'invest_pref' => 2,
            'invest_stake' => 35,
            'full_acquisition' => 1,
            'purchase_capacity_min' => 75000000.0000,
            'purchase_capacity_max' => 75000000.0000,
            'inv_abt_urself' => 'Serial entrepreneur turned investor.',
            'linkedin_profile' => 'https://linkedin.com/in/example',
            'company_name' => 'GreenEarth Enterprises',
            'company_designation' => 'CTO',
            'company_placeid' => 'Another sample entry',
            'company_city' => 'Delhi',
            'company_state' => 'Delhi',
            'company_country' => 'United States',
            'company_pincode' => '110001',
            'company_website' => 'https://linkedin.com/in/example',
            'company_logo_path' => 'uploads/images/sample2.jpg',
            'company_summary' => 'A comprehensive overview of business strategies, growth opportunities, and market trends in the current landscape.',
            'inv_profile_pic_path' => 'uploads/images/sample2.jpg',
            'inv_profile_status' => 1,
            'membership_paid' => 2,
            'membership_plan' => 2,
            'inv_profile_pic_name' => 'uploads/images/sample2.jpg',
            'trackid' => 'TRK1001',
            'utm_source' => 'Trending',
            'utm_medium' => 'facebook',
            'utm_campaign' => 'facebook',
            'contact_response' => 15,
            'contact_status' => 1,
            'activated_by' => 2,
            'activated_at' => '2025-02-02 10:30:00',
            'last_login_at' => '2025-02-02 10:30:00',
            'reg_source' => 2
        ]);

        DB::table('profile_investor')->insert([
            'investor_id' => 3,
            'inv_profile_str' => 'LEN0003',
            'user_id' => 3,
            'inv_name' => 'Amit Patel',
            'inv_email' => 'priya.sharma@example.com',
            'inv_mobile' => '7654321098',
            'inv_placeid' => 'Third sample value',
            'inv_city' => 'Bangalore',
            'inv_state' => 'Karnataka',
            'inv_country' => 'Singapore',
            'inv_headline' => 'How to Scale Your Startup',
            'inv_intro' => 'Detailed analysis covering key aspects of business operations, market competition, and potential areas for expansion.',
            'inv_type' => 3,
            'firm_type' => 3,
            'invest_size_min' => 1500.0000,
            'invest_size_max' => 1500.0000,
            'invest_pref' => 3,
            'invest_stake' => 50,
            'full_acquisition' => 0,
            'purchase_capacity_min' => 100000000.0000,
            'purchase_capacity_max' => 100000000.0000,
            'inv_abt_urself' => 'Fund manager with global exposure.',
            'linkedin_profile' => 'https://company.com',
            'company_name' => 'SkyRocket Innovations',
            'company_designation' => 'Managing Director',
            'company_placeid' => 'Third sample value',
            'company_city' => 'Bangalore',
            'company_state' => 'Karnataka',
            'company_country' => 'Singapore',
            'company_pincode' => '560001',
            'company_website' => 'https://company.com',
            'company_logo_path' => 'uploads/images/sample3.jpg',
            'company_summary' => 'Detailed analysis covering key aspects of business operations, market competition, and potential areas for expansion.',
            'inv_profile_pic_path' => 'uploads/images/sample3.jpg',
            'inv_profile_status' => 0,
            'membership_paid' => 1,
            'membership_plan' => 1,
            'inv_profile_pic_name' => 'uploads/images/sample3.jpg',
            'trackid' => 'TRK1002',
            'utm_source' => 'Latest',
            'utm_medium' => 'linkedin',
            'utm_campaign' => 'linkedin',
            'contact_response' => 25,
            'contact_status' => 0,
            'activated_by' => 3,
            'activated_at' => '2025-03-03 10:30:00',
            'last_login_at' => '2025-03-03 10:30:00',
            'reg_source' => 3
        ]);

    }
}